# Example Dex Configuration
# Place this file at .dex/config.yml in your project

defaults:
  format: claude          # Default output format
  depth: focused         # Default extraction depth
  clipboard: true        # Always copy to clipboard

filters:
  ignorePaths:
    - .claude
    - node_modules
    - dist
    - build
    - .git
    - .dex
    - coverage
    - "*.min.js"
    - "*.min.css"

# For custom prompts, create .yml files in .dex/prompts/
# Example: .dex/prompts/team-review.yml
#
# name: Team Code Review
# description: Our team's review process
# extends: base-review
# instructions: |
#   Follow our team's coding standards:
#   - TypeScript strict mode
#   - 80% test coverage minimum
#   - Performance benchmarks required